### ISSUE TITLE
Rename SRIOV_USERSPACE to something more explicit

### ISSUE THREAD

**Issue by fkautz** [networkservicemesh/api#15]
The current mechanism name is SRIOV_USERSPACE. This is a network service centric view of the world. The client connects in via a standard interface type which we didn't historically have in NSM. 

@przemeklal In order to retain convention and accuracy, can you suggest a new name and open a PR refactoring the name? I think you're in the best position to suggest a good name here.

**Comment by przemeklal** [comment]
Sure, I'll be happy to.

Okay, so what we know so far about *this* mechanism:
1. It uses HW based network interfaces - SR-IOV Virtual Functions or Physical Functions.
Using any other type of interface doesn't make much sense at this stage. Initially I thought that *in the future* we may consider solutions like e.g. port representors for OVS-DPDK offloaded to the HW. However based on the initial feedback in the design spec, you guys see this is as totally unrelated - fine. Following this logic we should also exclude any other types of userspace networking interfaces such as virtio-user, vhostuser and memif (which has its own plugin).
Based on that, I think these could be make sense if included in the name:

- SRIOV
- NIC
- PCI_DEV, PCI_DEVICE, DEVICE
- NETWORK_ADAPTER
- PHYSICAL (rather bad because paravirtualized or software NICs can also be used)
- PHYS, PHYS_NET, PHYSNET, PHYS_ADAPTER
- HARDWARE, HW_NET, HW_LINK
- HOST, HOST_NIC, HOST_INTERFACE, HOST_OS_NIC (what if the interface is passed through to a VM using VT-x?) 
- INTERFACE, LINK, NET (maybe too generic)

2. Mechanism will use userspace networking, which means the interface will be attached to *some* userspace driver which will make it consumable by userspace based poll-mode driver application implemented with e.g. DPDK. What kind of drivers are supported - we don't know and we don't care. Some of you proposed to include VIFO in the name. That's a huge no from me. The landscape changes all the time, new kernel versions introduce new mechanisms. Intel NICs can be used with any of vfio-pci, igb_uio or uio_pci_generic kernel module. It's not our problem.
Having said that, the only common thing is that they run in userspace and are meant to provide acceleration, bypass the kernel and most people will use it with DPDK. Hence the proposed names:

- USERSPACE
- ACCELERATED, ACCEL (too vague)
- USER, USERSPACE_DATAPATH
- PMD (poll mode driver)
- DPDK (tho we shouldn't limit it to one tech when there's tech like ODP)

Now I'd like to ask you to combine something from the above lists that sounds best, personally I think these look okay:

- USERSPACE_NIC
- USERSPACE_HW_LINK
- ACCELERATED_INTERFACE (though it can mean anything really)
- ACCELERATED_DEVICE (better)
- USERSPACE_DEVICE
- SRIOV_USERSPACE
- USERSPACE_NET

**Comment by edwarnicke** [comment]
@przemeklal I wanted to ask a few questions to make sure I understand correctly... we are in this case injecting vfio devices, correct?

And a vfio device could be backed by an SRIOV VF, PF,  or non-SRIOV NIC, is that correct?

I guess what I'm trying to get at is that if I'm correct (and I would welcome correction if I'm wrong)... if feels like the vfio is the thing...

**Comment by edwarnicke** [comment]
Added #18 and #19 for discussion.

**Comment by nickolaev** [comment]
The naming can be mostly lead by this:
https://doc.dpdk.org/guides/linux_gsg/linux_drivers.html

They basically describe that we have:
1. UIO - a small kernel module to set up the device, map device memory to user-space and register interrupts.
2. VFIO - a more robust and secure driver in compare to the UIO, relying on IOMMU protection 
3. Bifurcated Driver - PMDs which use the bifurcated driver co-exists with the device kernel driver. On such a model, the NIC is controlled by the kernel, while the data path is performed by the PMD directly on top of the device.

Now saying this my preference is:
 - HOST_INTERFACE - to refer to a device which has a Linux kernel driver bound to it and exposed asa kerne interface on the host
 - HOST_DEVICE - to refer to a device which is bound to a non-kernel driver

@przemeklal has the question " (what if the interface is passed through to a VM using VT-x?). My answer is - even in that case, the HOST refers to the affiliation of that particular device with the physical or virtual hardware that is hosting the workload we are provisioning network for. So to me HOST has a pretty concrete meaning, no matter if we talk bare metal, virtualized HW, or even nested virtualization.

**Comment by przemeklal** [comment]
> * HOST_INTERFACE - to refer to a device which has a Linux kernel driver bound to it and exposed asa kerne interface on the host
> * HOST_DEVICE - to refer to a device which is bound to a non-kernel driver

+1 both names make sense to me

> @przemeklal has the question " (what if the interface is passed through to a VM using VT-x?). My answer is - even in that case, the HOST refers to the affiliation of that particular device with the physical or virtual hardware that is hosting the workload we are provisioning network for. So to me HOST has a pretty concrete meaning, no matter if we talk bare metal, virtualized HW, or even nested virtualization.

That's my understanding of the term *host* as well.

**Comment by mdr78** [comment]
> 1. UIO - a small kernel module to set up the device, map device memory to user-space and register interrupts.

I would suggest ignoring UIO for the moment.
It's inherent lack of security is 100% not what you want in a Cloud.

**Comment by mdr78** [comment]
> * HOST_DEVICE - to refer to a device which is bound to a non-kernel driver

I am not sure I like this name. For instance in the bifurcated driver model you are provisioning a queue-pair, not a device (pci or otherwise). In the case of RDMA the device is shared between multiple containers instead of being provision for one. 

Would HOST_INTERFACE_BYPASS as a cover all, work instead?

**Comment by edwarnicke** [comment]
I think this has been covered by #18 and #19, do folks agree?
